# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=200)),
                ('company_city', models.CharField(max_length=50)),
                ('company_state', models.CharField(max_length=2)),
                ('company_zip', models.CharField(max_length=15)),
                ('company_contact_person', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_date', models.DateField(verbose_name='date of debt')),
                ('debt_amount', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=100)),
                ('debtor_address', models.CharField(max_length=200)),
                ('debtor_city', models.CharField(max_length=50)),
                ('debtor_state', models.CharField(max_length=2)),
                ('debtor_zip', models.CharField(max_length=15)),
                ('debtor_dob', models.DateField(verbose_name='date of birth')),
                ('debtor_phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor'),
        ),
        migrations.AddField(
            model_name='comments',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor'),
        ),
    ]
