# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=255)),
                ('comment_date', models.DateTimeField(verbose_name='date of comment')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=200)),
                ('company_city', models.CharField(max_length=50)),
                ('company_state', models.CharField(max_length=2)),
                ('company_zip', models.CharField(max_length=15)),
                ('company_contact_person', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causeNumber', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=1)),
                ('race', models.CharField(max_length=3)),
                ('offense_text', models.CharField(default='MM', max_length=100)),
                ('offense_type', models.CharField(default='MM', max_length=10)),
                ('case_text', models.CharField(default='MM', max_length=20)),
                ('disposition_text', models.CharField(default='MM', max_length=40)),
                ('judgement_text', models.CharField(default='MM', max_length=40)),
                ('sentence_text', models.CharField(default='MM', max_length=40)),
                ('fine_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_date', models.DateField(verbose_name='date of debt')),
                ('debt_amount', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=100, unique=True)),
                ('debtor_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor'),
        ),
        migrations.AddField(
            model_name='dcontact',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor'),
        ),
        migrations.AddField(
            model_name='crime',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
