# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 11:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debtors', '0003_auto_20160519_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 11, 56, 50, 442098, tzinfo=utc), verbose_name='date of comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debtor',
            name='debtor_added_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
