# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0004_auto_20160519_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causeNumber', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=1)),
                ('race', models.CharField(max_length=3)),
                ('dob', models.DateTimeField(verbose_name='date of birth')),
                ('offense_date', models.DateTimeField(verbose_name='date of offense')),
                ('offense_text', models.CharField(max_length=100)),
                ('offense_type', models.CharField(max_length=10)),
                ('case_text', models.CharField(max_length=20)),
                ('disposition_text', models.CharField(max_length=40)),
                ('judgement_date', models.DateTimeField(verbose_name='date of judgement')),
                ('judgement_text', models.CharField(max_length=40)),
                ('sentence_text', models.CharField(max_length=40)),
                ('sentence_start_date', models.DateTimeField(verbose_name='date of sentence start')),
                ('sentence_stop_date', models.DateTimeField(verbose_name='date of sentence stop')),
                ('fine_amount', models.IntegerField(max_length=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='debtor_dob',
        ),
        migrations.AddField(
            model_name='crime',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor'),
        ),
    ]
