# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0004_auto_20160521_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='id',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debtor_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
