# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0005_auto_20160519_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='fine_amount',
            field=models.IntegerField(),
        ),
    ]
