# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0006_auto_20160519_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='fine_amount',
        ),
    ]
