# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0006_auto_20160521_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcontact',
            old_name='debtor',
            new_name='debtor_name',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debtor_added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
