# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0007_auto_20160522_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcontact',
            name='debtor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor', to_field='debtor_name'),
        ),
    ]
