# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0007_remove_crime_fine_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='case_text',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='disposition_text',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='judgement_date',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='judgement_text',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='offense_date',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='offense_text',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='offense_type',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='race',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='sentence_start_date',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='sentence_stop_date',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='sentence_text',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='sex',
        ),
    ]
