# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0008_auto_20160519_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='race',
            field=models.CharField(default='M', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crime',
            name='sex',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
