# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0008_auto_20160522_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='id',
        ),
        migrations.AlterField(
            model_name='dcontact',
            name='debtor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debtor_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
