# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0009_auto_20160519_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='case_text',
            field=models.CharField(default='MM', max_length=20),
        ),
        migrations.AddField(
            model_name='crime',
            name='disposition_text',
            field=models.CharField(default='MM', max_length=40),
        ),
        migrations.AddField(
            model_name='crime',
            name='dob',
            field=models.DateTimeField(default=datetime.date(2014, 4, 4), verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='crime',
            name='fine_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crime',
            name='judgement_date',
            field=models.DateTimeField(default=datetime.date(2014, 4, 4), verbose_name='date of judgement'),
        ),
        migrations.AddField(
            model_name='crime',
            name='judgement_text',
            field=models.CharField(default='MM', max_length=40),
        ),
        migrations.AddField(
            model_name='crime',
            name='offense_date',
            field=models.DateTimeField(default=datetime.date(2014, 4, 4), verbose_name='date of offense'),
        ),
        migrations.AddField(
            model_name='crime',
            name='offense_text',
            field=models.CharField(default='MM', max_length=100),
        ),
        migrations.AddField(
            model_name='crime',
            name='offense_type',
            field=models.CharField(default='MM', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='sentence_start_date',
            field=models.DateTimeField(default=datetime.date(2014, 4, 4), verbose_name='date of sentence start'),
        ),
        migrations.AddField(
            model_name='crime',
            name='sentence_stop_date',
            field=models.DateTimeField(default=datetime.date(2014, 4, 4), verbose_name='date of sentence stop'),
        ),
        migrations.AddField(
            model_name='crime',
            name='sentence_text',
            field=models.CharField(default='MM', max_length=40),
        ),
    ]
