# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0009_auto_20160522_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcontact',
            name='debtor_name',
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='debtor',
            new_name='debtor_name',
        ),
        migrations.AddField(
            model_name='crime',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='zip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='phone',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='zip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='case_text',
            field=models.CharField(default='MM', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='disposition_text',
            field=models.CharField(default='MM', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='fine_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='judgement_text',
            field=models.CharField(default='MM', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='offense_text',
            field=models.CharField(default='MM', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='offense_type',
            field=models.CharField(default='MM', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='race',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='sentence_text',
            field=models.CharField(default='MM', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='DContact',
        ),
    ]
