# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0010_auto_20160522_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='id',
        ),
        migrations.AlterField(
            model_name='crime',
            name='causeNumber',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
