# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0013_auto_20160522_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime',
            old_name='debtor_name',
            new_name='debtor',
        ),
    ]
